### ISSUE TITLE
3주차 진행

### ISSUE THREAD

**Issue by gyeongwon1275** [CodeSoom/project-react-3-gyeongwon1275#58]
## Incompleted 2주차

- [ ] 사용자는 특정 이미지 게시물에 댓글을 등록할 수 있다. 
- [ ] 사용자는 특정 이미지 게시물에 좋아요, 싫어요를 반영할 수 있다.
- [ ] 사용자는 회원가입을 할 수 있다. 
- [ ] 사용자는 로그인을 할 수 있다.

## TODO 3주차

- [ ] 사용자는 특정 이미지 게시물에 댓글을 등록할 수 있다. 
- [ ] 사용자는 특정 이미지 게시물에 좋아요, 싫어요를 반영할 수 있다.
- [ ] 사용자는 회원가입을 할 수 있다. 
- [ ] 사용자는 로그인을 할 수 있다.
- [ ] 사용자는 profile image 를 설정할  수 있다. 
- [ ] 사용자가 profile image 를 설정하지 않으면 임의로 지정된다. 
- [ ] 사용자는 특정 이미지를 다운받을 수 있다. 
- [ ] 사용자는 자신이 작성한 이미지 게시물을 삭제할 수 있다. 
- [ ] 사용자는 자신이 작성한 이미지 게시물을 수정할 수 있다.

**Comment by moonkii** [comment]
개인적인 견해로는 작업량이 많아 보이기도 해서 3주차 안에 TODO 가 모두 가능 할까요??

해야할 일과 이번주 할 수 있는 작업량을 구분하면 좋을 것 같아요.
