### ISSUE TITLE
4주차 진행

### ISSUE THREAD

**Issue by gyeongwon1275** [CodeSoom/project-react-3-gyeongwon1275#94]
## Incompleted 3주차

- [ ] 사용자는 특정 이미지 게시물의 댓글갯수를 확인할 수 있다.  
- [ ] 사용자는 특정 이미지 게시물에 좋아요, 싫어요를 반영할 수 있다.
- [ ] 사용자는 특정 이미지 게시물의 좋아요, 싫어요 갯수를 확인할 수 있다.
- [ ] 사용자는 특정 이미지를 다운받을 수 있다. 

## TODO 4주차

- [ ] 사용자는 desktop, mobile 환경에 맞는 메인page 를 볼 수 있다.
- [ ] 사용자는 desktop, mobile 환경에 맞는 이미지 상세 page를 볼 수 있다.
- [ ] 사용자는 특정 이미지 게시물의 댓글갯수를 확인할 수 있다.  
- [ ] 사용자는 사용자 정보를 수정할  수 있다. 
- [ ] 사용자는 특정 이미지를 다운받을 수 있다. 
- [ ] 사용자는 특정 이미지 게시물에 좋아요, 싫어요를 반영할 수 있다.
- [ ] 사용자는 특정 이미지 게시물의 좋아요, 싫어요 갯수를 확인할 수 있다.

**Comment by Kihyun92** [comment]
3주차에서 많은 작업들이 넘어왔군요. 작성하신 계획들은 프로젝트 완성에 필요한 부분들일 거에요. 물론 이번주 내로 완성하면 좋겠지만, 일주일 동안 다 진행하기 힘들 수 있을 것 같기도해요.

본인이 생각하는 서비스의 가치를 전달하기 위해서 꼭 필요한 기능들부터 우선순위를 짜보고, 현실적인 4주차 계획을 세워보셔도 좋을 것 같습니다. 나머지 TODO들은 백로그에 두고, 개인적으로 5주, 6주 계획을 세우면서 해결해가도 좋을 것 같습니다. 😊
